name: Publish
run-name: Publishing the package to NPM

on:
    release:
        types: [released]

jobs:
    # Packages and publishes the package to NPM
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            # Setting up Node
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
                  registry-url: https://registry.npmjs.org/

            # Installing dependencies
            - run: yarn

            # Publishing to NPM
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
